<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="CompositeApp1" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://j2ee.netbeans.org/wsdl/AuthBPEL/ClientAuthWSDL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="CompositeApp1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://j2ee.netbeans.org/wsdl/AuthBPEL/ClientAuthWSDL" location="http://laure-HP-EliteBook-Folio-9470m:9080/CompositeApp1-sun-http-binding/AuthBPEL/ClientAuthWSDL.wsdl">
    </import>
  <portType name="dummyCasaPortType">
  </portType>
  <binding name="casaBinding1" type="ns:ClientAuthWSDLPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getClientAuthOperation">
      <soap:operation/>
      <input name="input1">
        <soap:body use="literal"/>
      </input>
      <output name="output1">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CompositeApp1Service1">
    <port name="casaPort1" binding="tns:casaBinding1">
      <soap:address location="http://laure-HP-EliteBook-Folio-9470m:9080/CompositeApp1Service1/casaPort1"/>
    </port>
  </service>
</definitions>
